/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.4-dev */

#ifndef PB_PROTOBUFS_SAMPLE_PB_H_INCLUDED
#define PB_PROTOBUFS_SAMPLE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _protobufs_SubTest {
    uint32_t sub_foo;
    uint64_t sub_bar;
} protobufs_SubTest;

typedef struct _protobufs_Test {
    uint32_t foo;
    uint32_t bar;
    bool baz;
    bool has_sub;
    protobufs_SubTest sub;
} protobufs_Test;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define protobufs_Test_init_default              {0, 0, 0, false, protobufs_SubTest_init_default}
#define protobufs_SubTest_init_default           {0, 0}
#define protobufs_Test_init_zero                 {0, 0, 0, false, protobufs_SubTest_init_zero}
#define protobufs_SubTest_init_zero              {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define protobufs_SubTest_sub_foo_tag            1
#define protobufs_SubTest_sub_bar_tag            2
#define protobufs_Test_foo_tag                   1
#define protobufs_Test_bar_tag                   2
#define protobufs_Test_baz_tag                   3
#define protobufs_Test_sub_tag                   4

/* Struct field encoding specification for nanopb */
#define protobufs_Test_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   foo,               1) \
X(a, STATIC,   SINGULAR, FIXED32,  bar,               2) \
X(a, STATIC,   SINGULAR, BOOL,     baz,               3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sub,               4)
#define protobufs_Test_CALLBACK NULL
#define protobufs_Test_DEFAULT NULL
#define protobufs_Test_sub_MSGTYPE protobufs_SubTest

#define protobufs_SubTest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sub_foo,           1) \
X(a, STATIC,   SINGULAR, FIXED64,  sub_bar,           2)
#define protobufs_SubTest_CALLBACK NULL
#define protobufs_SubTest_DEFAULT NULL

extern const pb_msgdesc_t protobufs_Test_msg;
extern const pb_msgdesc_t protobufs_SubTest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define protobufs_Test_fields &protobufs_Test_msg
#define protobufs_SubTest_fields &protobufs_SubTest_msg

/* Maximum encoded size of messages (where known) */
#define protobufs_Test_size                      30
#define protobufs_SubTest_size                   15

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
