/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4-dev */

#include "sample.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(protobufs_Test, protobufs_Test, AUTO)


PB_BIND(protobufs_SubTest, protobufs_SubTest, AUTO)



